const CoursesDict = {
    "1BA" : ["1bacp10",	"1baem10","1baic10","1bamc10","1bamd10","1bamm10","1bapi10",
             "1bapm10","1baps10","1bast10","1bate10"]
    ,
    "2BA" : ["2bach20","2badt20","2bael20","2baeo20","2bain20","2bala20","2bamf20",
             "2baom20","2baph20","2barm20","2bath20","2batm20","2beea20","2bepi20"]
    ,
    "3BE" : [],
    "3BM" : [],
    "3BS" : [],
    '4MEM': [],
    '4MAU': [],
    '4MIN': [],
    '4MCO': [],
    '4MGE': [],
    '4MIS': [],
    '4MBA': [],
    '4MEO': [],
    '5MEM': [],
    '5MAU': [],
    '5MIN': [],
    '5MCO': [],
    '5MGE': [],
    '5MIS': [],
    '5MBA': [],
    '5MEO': [],
    '5MIC': [],
}

const CoursesCodes = {
        "1bacp10": "Chimie-Physique",	
        "1baem10": "Electricité et outils mathématiques",	
        "1baic10": "Informatique et communication",
        "1bamc10": "Science du mouvement - Cinématique",	
        "1bamd10": "Science du mouvement - Dynamique",	
        "1bamm10": "Science des matériaux",	
        "1bapi10": "Projet intégrateur",	
        "1bapm10": "Pont vers le supérieur : mathématiques",
        "1baps10": "Pont vers le supérieur : Sciences",	
        "1bast10": "Stabilité",	
        "1bate10": "Technologie",
        "2bach20": "Chimie du vivant et environnement",
        "2badt20": "Dessin technique",
        "2bael20": "Electricité",
        "2baeo20": "Electronique",
        "2bain20": "Informatique",
        "2bala20": "Langues",
        "2bamf20": "Mécanique des fluides et transfert de chaleur",
        "2baom20": "Outils mathématiques",
        "2baph20": "Onde, optique et physique moderne",
        "2barm20": "Stabilité, déformation et résistance des structure",
        "2bath20": "Thermodynamique",
        "2batm20": "Mesures",
        "2beea20": "Electronique appliquée",
        "2bepi20": "Projet informatique"
}

export default { CoursesDict, CoursesCodes };
